### ISSUE TITLE
Python backend setup

### ISSUE THREAD

**Issue by stuartlynn** [Urban-Analytics-Technology-Platform/web-app-template#16]
In addition to a rust backend we want to have the ability to have a python backend using pyodide. We should draw from the work on demoland to generate a pyodide environment and run code there.

Some questions 

- Do we want to initially limit ourselves to pyodide supported packages? Or do we want to including tooling to include custom wheels.
- Pyodide shouldn't require a build step so it feels like this is more like a utility function 
- How do we define a common interface for this, Rust and API servers to allow us to more easily support each.

**Comment by dabreegster** [comment]
I think a nice first step would be wiring up the equivalent of the tiny Rust backend in a web worker, just to see how the config/build steps work. A second would be including some dependencies like osmnx and networkx that get used in practice, to see how pure Python and things with system deps work. A first real use case is to let Hussein and Chris experiment with some GTFS routing from the comforts of Python, but wiring up to maplibre.

**Comment by dabreegster** [comment]
References:
https://github.com/Urban-Analytics-Technology-Platform/demoland-web/tree/main/src/lib/python
https://www.npmjs.com/package/pyodide

**Comment by dabreegster** [comment]
- [ ]  The python backend should probably be built as a wheel, so it can grow to multiple files
- [ ] The Svelte template app hardcodes a Python or Rust backend now. Probably the CLI tool generating the template could just generate one or the other, based on what the user chooses
