### ISSUE TITLE
Stub out generator script

### ISSUE THREAD

**Issue by stuartlynn** [Urban-Analytics-Technology-Platform/web-app-template#17]
We eventually want to have a generator script to allow folks to answer a few different questions and generate a scaffolded app.

This seems to be mostly including a script in the ```bin``` section of the package.json which runs the process to scaffold out the project.

**Comment by penelopeysm** [comment]
For example we'd like the generator script to let the user choose between a Rust and Python 'backend' which is currently hardcoded:

https://github.com/Urban-Analytics-Technology-Platform/web-app-template/blob/fcdc3253b29cc80e8116c448738d7c3cdb72641a/template_app/src/routes/%2Bpage.svelte#L14-L17
