### ISSUE TITLE
Charting library

### ISSUE THREAD

**Issue by dabreegster** [Urban-Analytics-Technology-Platform/web-app-template#6]
Using plotly directly with Svelte was tedious as of a year ago: https://github.com/alan-turing-institute/uatk-spc/blob/6a5f1e772310422b254c048cc13b01f92e48bcf3/web/components/Plots.svelte#L109

**Comment by dabreegster** [comment]
If it's helpful, I have a few other uses of charting in Svelte from more recent work:

https://github.com/acteng/inspectorate_tools/blob/3030ec8320e62ba56a3c59c7a2654b46eef12cc6/src/routes/route_check/results_summary/LevelOfServiceTable.svelte#L77
Chartjs svelte wrapper is pretty great, though [registering](https://github.com/acteng/inspectorate_tools/blob/3030ec8320e62ba56a3c59c7a2654b46eef12cc6/src/routes/route_check/results_summary/LevelOfServiceTable.svelte#L27) is a bit boilerplatey

https://github.com/Urban-Analytics-Technology-Platform/od2net/blob/main/viewer/src/TradeoffRadar.svelte
An interactive radar chart, using a plugin

**Comment by sgreenbury** [comment]
- For demo chart could: 1) include random data or 2) an example geojson
- utility methods for transformations from geojson to data in form required by `svelte-chartjs` (see DemoLand for an example too, e.g. callbacks just updating the data of chart)
- Styling, selecting subsets/ranges with callbacks, check how fully-featured it is then add components if needed to wrap functionality not available immediately (e.g. interactivity mentioned above)

Next step: add initial version with random data/geojson data directly to main app template with interactive features, then consider refactoring into a component/utils if lots of code
